Don't check for build before releasing (plushu/plusku#2)

diff --git a/subcommands/empty b/subcommands/empty
--- a/subcommands/empty
+++ b/subcommands/empty
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
+set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x
 
 if [[ -n "$PLUSHU_APP_NAME" ]]; then
   app=$PLUSHU_APP_NAME
@@ -12,15 +12,16 @@ else
 fi
 
 app_dir=$PLUSHU_ROOT/apps/$app
-env_file=$app_dir/config.env
 
-# Check if app exists with the same name
-if [ ! -d "$app_dir" ]; then
-  echo "App $app does not exist" >&2
+# Check if app exists
+if [[ ! -d "$app_dir" ]]; then
+  echo "App not found: $app" >&2
   exit 1
 fi
 
-if [ ! -f "$env_file" ]; then
+env_file=$app_dir/config.env
+
+if [[ ! -f "$env_file" ]]; then
   touch "$env_file"
 fi
 
@@ -34,9 +35,6 @@ else
   > "$env_file"
 fi
 
-# If there is a build image to base a release on
-if [[ -f "$app_dir/build.iid" ]]; then
-  # Restart app with new configuration
-  "$PLUSHU_ROOT/lib/plushook" release-app "$app"
-  "$PLUSHU_ROOT/lib/plushook" deploy-app "$app"
-fi
+# Restart app with new configuration
+"$PLUSHU_ROOT/lib/plushook" release-app "$app"
+"$PLUSHU_ROOT/lib/plushook" deploy-app "$app"
diff --git a/subcommands/pretty b/subcommands/pretty
--- a/subcommands/pretty
+++ b/subcommands/pretty
@@ -12,15 +12,16 @@ else
 fi
 
 app_dir=$PLUSHU_ROOT/apps/$app
-env_file=$app_dir/config.env
 
-# Check if app exists with the same name
-if [ ! -d "$app_dir" ]; then
-  echo "App $app does not exist" >&2
+# Check if app exists
+if [[ ! -d "$app_dir" ]]; then
+  echo "App not found: $app" >&2
   exit 1
 fi
 
-if [ ! -f "$env_file" ]; then
+env_file=$app_dir/config.env
+
+if [[ ! -f "$env_file" ]]; then
   touch "$env_file"
 fi
 
